-- ==========================================
-- Tabela USUARIO
-- ==========================================
CREATE TABLE "USUARIO" (
    "IDUSUARIO" SERIAL PRIMARY KEY,
    "NOMEUSUARIO" VARCHAR(16) NOT NULL,
	"NOMECOMPLETO" VARCHAR(200) NOT NULL,
    "SENHA" VARCHAR(16) NOT NULL,
    "EMAIL" VARCHAR(255),
    "ENDERECO" VARCHAR(255),
    "CIDADE" VARCHAR(150),
    "ESTADO" VARCHAR(100),
    "DATACADASTRO" TIMESTAMP,
    "DATAATUALIZACAO" TIMESTAMP
);

-- ==========================================
-- Tabela MOVIMENTACAO
-- ==========================================
CREATE TABLE "MOVIMENTACAO" (
    "IDMOVIMENTACAO" SERIAL PRIMARY KEY,
	"DESCRICAOMOVIMENTACAO" VARCHAR(100) NOT NULL,
    "VALORMOVIMENTADO" FLOAT NOT NULL,
	"DATAMOVIMENTACAO" TIMESTAMP NOT NULL,
    "TIPOMOVIMENTACAO" VARCHAR(16) NOT NULL,
    "FIXA" BOOLEAN,
    "IDUSUARIO" INTEGER,
	CONSTRAINT FK_IDUSUARIO  FOREIGN KEY ("IDUSUARIO") REFERENCES "USUARIO"("IDUSUARIO") ON DELETE CASCADE
);
